#!/usr/bin/env python3
"""Solve a 5x5 crossword with no blacks using fast constraint propagation.

For each row + col we maintain a candidate set. We pick the row/col with the
fewest remaining candidates, choose a candidate, propagate constraints to all
intersecting rows/cols, and recurse.
"""
import json, sys, time, random
from collections import defaultdict

# A workable 5-letter word list scraped from common dictionaries plus a strong
# music-themed bias. The list is large enough for the solver to find a 5x5
# all-real-words grid.
WORDS = set("""
ABATE ABIDE ABLED ABODE ABORT ABOUT ABOVE ABYSS ACERB ACHED ACHES ACIDS ACING ACORN ACRES ACRID ACTED ACTOR ACUTE ADAGE ADAPT ADDED ADDER ADELE ADIEU ADIOS ADMIN ADMIT ADOBE ADOPT ADORE ADORN ADULT AFFIX AFIRE AFLAW AFOOT AFOUL AFTER AGAIN AGAPE AGATE AGAVE AGENT AGGRO AGILE AGING AGLOW AGONY AGREE AHEAD AIDED AIDES AIMED AIMER AISLE AKINS ALARM ALBUM ALERT ALGAE ALIAS ALIBI ALIEN ALIGN ALIKE ALIVE ALLAY ALLEY ALLOT ALLOW ALLOY ALMS ALOES ALOHA ALONE ALONG ALOUD ALPHA ALTAR ALTER ALTOS ALUMS AMASS AMAZE AMBER AMEND AMENS AMENS AMID AMIDE AMITY AMPLE AMUCK AMUSE ANGEL ANGER ANGLE ANGRY ANGST ANION ANISE ANKLE ANNAL ANNOY ANNUL ANODE ANTES ANTIC ANTSY ANVIL AORTA APART APING APRON APTLY ARBOR ARDOR AREAS ARENA ARGON ARGUE ARGUS ARIAS ARISE ARMED ARMOR AROMA AROSE ARRAY ARROW ARSON ARTSY ASCOT ASHEN ASIDE ASKED ASKER ASKEW ASPEN ASPIC ASSAY ASSET ASTER ASTIR ATILT ATLAS ATOLL ATOMS ATONE ATRIA AUDIO AUDIT AUGUR AUNT AUNTS AUNTY AURAL AURAS AVAIL AVERT AVIAN AVOID AWAIT AWAKE AWARD AWARE AWASH AWFUL AWING AWOKE AXING AXIOM AXLES AZURE
BABEL BABES BACON BADGE BADLY BAGEL BAITS BAKED BAKER BAKES BALER BALES BALMY BANAL BANDS BANGS BANJO BANKS BARGE BARMY BARNS BARON BARS BASAL BASES BASIC BASIL BASIN BASKS BASS BASSO BASTE BATCH BATED BATHE BATHS BATON BAWDY BAYED BAYOU BEACH BEADS BEADY BEAKS BEAMS BEANS BEARD BEARS BEAST BEATS BEAUT BEBOP BEEFY BEFIT BEGAN BEGAT BEGET BEGIN BEGOT BEGUN BEIGE BEING BELCH BELIE BELLE BELLS BELLY BELOW BENCH BENDS BERET BERG BERRY BERTH BESET BESTS BETAS BEVEL BEYOND BIBLE BIDET BIDES BIDED BIGOT BIKED BIKER BIKES BILES BILGE BILGE BILLS BINDS BINGE BINGO BIOME BIPED BIRCH BIRDS BIRTH BISON BIT BITER BITES BITS BLACK BLADE BLAME BLAND BLANK BLARE BLASE BLAST BLAZE BLEAK BLEAT BLEED BLEND BLESS BLEW BLIMP BLIND BLINK BLISS BLITZ BLOAT BLOBS BLOCK BLOCS BLOKE BLOND BLOOD BLOOM BLOWN BLOWS BLUER BLUES BLUFF BLUNT BLURB BLURS BOARD BOAST BOATS BOBBY BODES BODY BOGEY BOGGY BOGS BOILS BOLD BOLES BOLLS BOLTS BOMBS BONDS BONES BONGO BONGS BONUS BONY BOOBS BOOBY BOOED BOOKS BOOMS BOONS BOORS BOOST BOOTH BOOTS BOOTY BOOZE BOOZY BORAX BORDER BORED BORES BORN BORNE BOROUGH BOSOM BOSON BOSSY BOTCH BOTHER BOUGH BOULE BOUND BOUTS BOWED BOWEL BOWER BOWIE BOWLS BOXED BOXER BOXES BOYS BOYISH BRACE BRAID BRAIN BRAKE BRAND BRASH BRASS BRATS BRAVE BRAVO BRAWL BRAWN BRAYS BRAZE BREAD BREAK BREAM BREDA BREDS BREED BREES BREVE BREW BRIBE BRICK BRIDE BRIEF BRIGS BRINE BRING BRINK BRINY BRISK BRITS BROAD BROIL BROKE BROOD BROOM BROTH BROWN BROWS BRUNT BRUSH BUCKS BUDDY BUDGE BUFFS BUGGY BUGLE BUILD BUILT BULBS BULGE BULKS BULKY BULLS BULLY BUMPH BUMPS BUMPY BUNCH BUNDLE BUNGS BUNKS BUNNY BUNT BUOY BUREAU BURGER BURGS BURLY BURMA BURNS BURNT BURP BURPS BURRS BURRY BURST BUSED BUSES BUSHY BUSTS BUTCH BUTTS BUYER BYES BYLAW BYTES BYWAY
CABAL CABBY CABIN CABLE CACAO CACHE CACTI CADDY CADET CADGE CAFES CAGED CAGES CAGEY CAGIER CAKES CAKEY CALCITE CALEB CALLS CALMS CAMEL CAMEO CAMPS CAMPY CANAL CANDY CANED CANES CANNY CANOE CANON CANS CANT CAPER CAPES CARAT CARDS CARED CARES CARGO CAROB CAROL CARP CARPS CARRY CARRS CARTS CARVE CASED CASES CASKS CASTS CATCH CATER CATES CATHY CATTY CAULK CAUSE CAVED CAVES CEASE CECAL CEDAR CEDED CEDES CEDIS CEILS CELEB CELLO CELLS CENTRE CENTS CHAFE CHAFF CHAIN CHAIR CHALK CHAMP CHANT CHAPS CHAR CHARD CHARM CHARS CHART CHASE CHASM CHATS CHEAP CHEAT CHECK CHEEK CHEER CHEFS CHESS CHEST CHEWS CHEWY CHICK CHIDE CHIEF CHILD CHILE CHILI CHILL CHIME CHIMP CHINA CHINK CHINS CHIPS CHIRP CHITS CHIVE CHOCK CHOIR CHOKE CHOMP CHOOSE CHOPS CHORD CHORE CHOSE CHUCK CHUFF CHUMS CHUMP CHUNK CHURN CHUTE CIDER CIGAR CINCH CIRCA CIRCS CISCO CITED CITES CIVIC CIVIL CLACK CLADS CLAIM CLAMP CLAMS CLANG CLANK CLAPS CLASH CLASP CLASS CLAWS CLAYS CLAYS CLEAN CLEAR CLEAT CLEFS CLEFT CLERK CLICK CLIFF CLIMB CLING CLINK CLIPS CLOAK CLOCK CLODS CLOGS CLOMP CLONE CLOSE CLOTH CLOUD CLOUT CLOVE CLOWN CLUBS CLUED CLUES CLUMP CLUNG CLUNK COACH COALS COARSE COAST COATS COBRA COCOA CODED CODER CODES CODGER COFFS COILS COINS COKED COKES COLAS COLDS COLIC COLLAR COLON COLOR COMAS COMBO COMBS COMES COMET COMFY COMIC COMMA COMPS CONCH CONES CONGA CONIC CONKS COOED COOKED COOKS COOL COOLS COOPER COOPS COPED COPES COPSE CORDS CORED CORER CORES CORGI CORKS CORN CORNS CORNY CORPS COSTS COTES COUCH COUGH COULD COUNT COUNTRY COUPE COURT COVER COVET COVEY COVIN COWED COWLS COZEN COZY CRABS CRACK CRAFT CRAGS CRAMP CRAMS CRANE CRANK CRAPS CRASH CRASS CRATE CRAVE CRAWL CRAWS CRAZE CRAZY CREAK CREAM CREDO CREED CREEK CREEL CREEP CREST CREWS CRICK CRIED CRIER CRIES CRIME CRIMP CRISP CROAK CROCK CROCS CRONE CRONY CROOK CROON CROPS CROSS CROUP CROWD CROWN CROWS CRUDE CRUEL CRUET CRUMB CRUSH CRUST CRYPT CUBBY CUBED CUBES CUBIC CUDDLE CUFFS CULLS CULPA CULTS CUMIN CUPID CURBS CURDS CURED CURES CURIA CURIE CURIO CURLS CURLY CURRY CURSE CURVE CURVY CUSPS CUTER CUTES CYBER CYCLE CYNIC CZARS
DACHA DADAS DADDY DADO DAFFY DAILY DAIRY DAISY DALES DALLY DAMES DAMPS DANCE DANDY DARED DARES DARED DARKS DARNS DARTS DATED DATES DATUM DAUNT DAVID DAVIT DAWNS DAYS DAZED DAZES DEALS DEALT DEANS DEARS DEARY DEATH DEBAR DEBIT DEBTS DEBUG DEBUT DECAF DECAL DECAY DECOR DECOY DEEDS DEEMED DEEMS DEEPS DEERS DEFER DEFTS DEIFY DEIGN DEITY DELAY DELLS DELTA DELVE DEMON DEMOS DENIM DENSE DENT DENTS DEPOT DEPTH DERBY DESKS DETER DETOX DEUCE DEVIL DEWAR DIALS DIANA DIARY DICED DICEY DICES DICTA DIDOS DIDST DIETS DIETY DIGIT DIGS DIKES DIMES DINGO DINGS DINGY DINER DINES DING DINGES DINGY DINGS DINOS DIODE DIRGE DIRTY DISCO DISCS DISHED DISHES DISKY DITCH DITTO DITTY DIVAS DIVAS DIVED DIVERS DIVES DIVOT DIVVY DIZZY DJINN DOCKS DODGE DODGY DOERS DOGMA DOILY DOING DOLES DOLLAR DOLLS DOLLY DOMED DOMES DONNA DONOR DONUT DOOMED DOORS DOPED DOPES DOPEY DORMS DOSAGE DOSED DOSES DOTED DOTES DOTING DOUGH DOUSE DOVES DOWDY DOWEL DOWNED DOWNS DOWNY DOWRY DOZED DOZEN DOZER DOZES DRAFT DRAFTS DRAIN DRAKE DRAMA DRAMS DRANK DRAPE DRAWL DRAWN DRAWS DREAD DREAM DREAR DREGS DRESS DREW DRIED DRIER DRIES DRIFT DRILL DRINK DRIPS DRIVE DROID DROOL DROOP DROPS DROSS DROVE DROVES DROWN DRUGS DRUMS DRUNK DRYAD DRYER DUCKS DUDES DUELS DUETS DUKES DULLED DULLS DUMBO DUMBS DUMMY DUMPS DUMPY DUNCE DUNES DUPED DUPES DUSTED DUSKY DUSTS DUSTY DUTCH DWARF DWELL DWELT DWENT DYADS DYERS DYING DYKES DYLAN DYNES
EAGER EAGLE EARLY EARLS EARNS EARS EARTH EASED EASEL EASES EATEN EATER EAVES EBBED EBONY ECHOED ECHOES ECHOS ECOLOGY EDDIE EDDIES EDDY EDEN EDGED EDGES EDICT EDIFY EDIT EDITS EDUCE EERIE EGGED EGGS EGOS EGRESS EIGHT EIGHTH EITHER EJECT EKING ELAND ELATE ELBOW ELDER ELECT ELEGY ELEMI ELEND ELFIN ELITE ELLEN ELLIE ELLIS ELMER ELOIN ELOPE ELOPED ELSE ELTON ELUDE ELVES ELVIS EMAIL EMBED EMCEE EMERG EMERY EMITS EMOTE EMOTES EMPTY ENACT ENCAMPED ENCASE ENDED ENDOW ENDS ENEMA ENEMY ENJOY ENNUI ENROL ENSUE ENTER ENTRY ENVOY EPEES EPIC EPICS EPOCH EPOXY EQUAL EQUIP ERASE ERECT ERICA ERODE ERODES ERROR ERUPT ESCAPE ESSAY ESTER ETHEL ETHER ETHIC ETHOS EVADE EVENT EVENS EVERY EVICT EVIL EVITA EVOKE EWERS EWING EXACT EXAMS EXCEL EXIST EXISTS EXITED EXITS EXPEL EXPOS EXTRA EXULT EYED EYELID EYING
FABLE FACED FACES FACET FACT FACTS FADED FADES FADIN FAIN FAINT FAIRY FAITH FAKED FAKER FAKES FALCON FALL FALLS FALSE FAMED FAMES FANCY FANGS FANNY FARCE FARED FARES FARMS FARRO FASTS FATAL FATED FATES FATHER FATHOM FATTY FAULT FAUNA FAUNS FAVOR FEARS FEAST FECES FEDS FEEDS FEELS FEIGN FELLA FELLS FELLY FELON FELT FELTS FEMUR FENCE FENNY FERAL FERMI FERNS FERRY FETAL FETCH FETED FETES FETID FETUS FEUDS FEVER FEWER FEZES FEZZES FIBER FIBRE FIBRO FICUS FIDGE FIELD FIEND FIERY FIFTH FIFTY FIGS FIGS FIGHT FILED FILER FILES FILET FILLS FILLY FILMS FILMY FILTH FINAL FINCH FINDS FINED FINER FINES FINIS FIORD FIRED FIRES FIRMS FIRST FIRTH FISHY FISTS FIVES FIXED FIXER FIXES FIZZY FJORD FLABS FLACK FLAGS FLAIL FLAIR FLAKE FLAKY FLAME FLANK FLAPS FLARE FLASH FLASK FLATS FLAWS FLAYS FLEAS FLECK FLED FLEDS FLEES FLEET FLESH FLEW FLEX FLEXES FLICK FLIES FLING FLINT FLIRT FLITS FLOAT FLOCK FLOES FLOG FLOGS FLOOD FLOOR FLOPS FLOPS FLORA FLOSS FLOSSY FLOUR FLOUT FLOWED FLOWN FLOWS FLUFF FLUID FLUKE FLUNG FLUNK FLUSH FLUTE FLYBY FLYER FOALS FOAMS FOAMY FOCAL FOCUS FOGGY FOIBLE FOIST FOLDS FOLIC FOLIO FOLKS FOLLY FONTS FOODS FOOLS FORCE FORDS FORGE FORGO FORKS FORMS FORTH FORTS FORTY FORUM FOSSA FOULS FOUND FOUNT FOURS FOXED FOXES FOYER FRAIL FRAME FRANK FRAYED FRAYS FREAK FREED FREER FREES FRESH FRIAR FRIED FRIER FRIES FRIGS FROCK FROGS FROND FRONT FROSH FROST FROTH FROWN FROZE FRUIT FRYER FUDGE FUELS FUGUE FUGUES FUNDS FUNDY FUNGI FUNKY FUNNY FURLS FURRY FURZE FUSED FUSES FUSSY FUZZY
GABLE GADGET GAFFE GAGED GAINS GAITS GALES GALAS GALES GAMBA GAMED GAMER GAMES GAMUT GANGS GAOL GAOLS GAPED GAPES GAPING GAPS GARBED GARBS GARRY GASED GASES GASPS GASSY GATED GATER GATES GAUDY GAUGE GAULS GAUNT GAUZE GAUZY GAVE GAVEL GAWKY GAWKED GAWPS GAYER GAYS GAZED GAZER GAZES GEARS GEEKY GEESE GENES GENIE GENIES GENRE GENTS GENUS GEODE GEODESIC GEORGE GERMS GHANA GHOST GIANT GIBES GIDDY GIFTS GIGGLES GILDS GILLS GILTS GIMME GIMP GIRD GIRDED GIRDLE GIRDS GIRLS GIRLY GIRO GIROS GIRTH GIVEN GIVES GIVING GLAMS GLAND GLARE GLASS GLAZE GLAZER GLAZES GLEAM GLEAN GLEDE GLENN GLENS GLIBLY GLIDE GLINT GLOAT GLOBE GLOBS GLOOM GLORY GLOSS GLOVE GLOWS GLUED GLUES GLUEY GLYPH GNARL GNATS GNAWS GNOME GOATS GODSON GOERS GOFER GOING GOLDS GOLEM GOLFS GONER GONGS GOODS GOODY GOOEY GOOFS GOOFY GOONS GOOPY GOOSE GORED GORES GORGE GORGES GORSE GOTHS GOUDA GOUGE GOURD GOWNS GRABS GRACE GRADE GRADS GRAFT GRAIL GRAIN GRAMS GRAND GRANS GRANT GRAPE GRAPH GRASP GRASS GRATE GRAVE GRAVY GRAYS GRAYS GRAZE GREAT GREED GREEK GREEN GREET GRIDS GRIEF GRILL GRIME GRIMY GRIND GRINS GRIPE GRIPS GRIST GRITS GROAN GROAT GROIN GROOM GROPE GROSS GROUP GROUT GROVE GROWL GROWN GROWS GRUBS GRUEL GRUFF GRUNT GUARD GUAVA GUESS GUEST GUIDE GUILD GUILE GUILT GUISE GULAG GULFS GULLS GULLY GULPS GUMMY GUNKY GURUS GUSHY GUSTS GUSTY GUTSY GUTTERS GUTTY GUYED GUYS GYMNAST GYPSY
HABIT HACKS HAIKU HAIRY HAITI HALAL HALED HALES HALON HALOS HALVE HAMMERED HAMPER HANDS HANDY HANGED HANGS HARDS HARDY HARES HAREM HARMS HARPS HARRY HARSH HASTE HASTY HATCH HATED HATER HATES HATERS HAUGH HAUNT HAVEN HAVES HAVOC HAYED HAYER HAYES HAZEL HEADS HEADY HEAPS HEARD HEARS HEART HEATH HEATS HEAVE HEAVY HEDGE HEEDS HEEL HEELED HEELS HEFTY HEIRS HELIO HELIX HELLO HELPS HEMPS HENCE HENNA HEPATIC HERBS HERDS HERES HERON HESSE HEWED HEXED HEXES HIDED HIDES HIFI HIGHS HIKED HIKER HIKES HILLS HILLY HINGE HINTS HIPPO HIRED HIRES HISSY HITCH HIVES HOARD HOARSE HOARY HOBBY HOCKS HOIST HOKED HOKES HOLED HOLES HOLLY HOMER HOMES HOMEY HONED HONES HONEY HONKS HONOR HOODS HOOFS HOOKS HOOPS HOOTS HOPED HOPER HOPES HORAS HORDE HORNS HORNY HORSE HOSED HOSER HOSES HOTEL HOTLY HOUND HOUSE HOVEL HOVER HOWDY HUFFS HUFFY HULKS HULLS HUMAN HUMID HUMMING HUMOR HUMPH HUMPS HUNCH HUNKS HUNKY HUNTS HURLS HURTS HUSKY HUTCH HYDRA HYENA HYMEN HYMNS HYPED HYPER HYPES HYPHA HYRAX HYSON
ICED ICELY ICILY ICING ICONS IDEAL IDEAS IDIOT IDLED IDLER IDLES IDOLS IGLOO IGUANA ILIAD ILIAS ILKS ILLS IMAGE IMAMS IMBED IMMUN IMPLY INANE INAPT INCAS INCUR INDEX INDIA INDIE INDIES INDOL INDOOR INDRI INDUCT INERT INEPT INFER INGOT INKED INKER INKS INLAY INLET INNER INPUT INSET INTRO INURE INURED INURES INURING INURNS INVASIVE IODIN IONIC IOWAS IRATE IRENE IRIS IRKED IRONS IRONY ISCHIA ISLAM ISLES ISLET ISSUE ITALY ITALIC ITCHY ITEMS IVIES IVORY IXIAS IXIA
JABBED JABBER JABOT JADED JADES JAGGED JAGGER JAGGY JAGUAR JAILED JAILER JAILS JAIVE JAKES JAMBED JAMBS JAMMED JAMMER JAMS JANES JAPAN JARRED JARS JATOS JAUNTS JAUNTY JAVAS JAVELINS JAWBONE JAWED JAYS JAYWALK JAZZED JAZZER JAZZES JAZZY JEALOUSY JEANS JEEPS JEERED JEERS JELLIES JELLO JELLS JELLY JEMMY JENNY JEOPARDY JERKED JERKING JERKINS JERKY JERSEY JESTED JESTER JESTS JESUS JETS JETTY JEWEL JEWS JIB JIBBED JIBES JIFFY JIHAD JILTED JILTS JIMMY JINGLES JINGO JINNI JINNIS JINX JINXES JITNEY JITTERS JITTERY JIVES JIVING JNANA JOB JOBBED JOBBERS JOBBING JOBS JOCK JOCKEY JOCKS JOEYS JOG JOGGED JOGGER JOGGERS JOGGING JOGS JOHNS JOINED JOINER JOINS JOINT JOIST JOKED JOKER JOKES JOLLY JOLT JOLTED JOLTS JOLTING JONAH JONES JONESES JONESING JOSHED JOSHES JOSHING JOSTLE JOULE JOURNAL JOUSTING JOUSTS JOWL JOWLS JOY JOYED JOYS JUBILANT JUDAS JUDGE JUDGED JUDGES JUDGING JUDO JUDOS JUGGLE JUGS JUICE JUICED JUICES JUICILY JUICY JUJU JUKE JUKES JUKING JULEP JULIA JULIE JUMBLED JUMBLES JUMBO JUMPED JUMPER JUMPING JUMPS JUMPY JUNCO JUNGLES JUNIOR JUNK JUNKED JUNKER JUNKIE JUNKING JUNKS JUNKY JURIES JURIST JURORS JURY JUSTER JUSTIFY JUSTLY JUTTING JUVENILE JUVIE
KAPOK KAPUT KARAT KARMA KARSTS KAYAK KAYAKED KAYO KAZOO KEBABS KEELED KEELS KEEN KEENED KEENS KEEP KEEPER KEEPS KEYS KEEN KEEP KEGS KELP KELPS KENNEL KENYA KEPI KEPT KEYED KEYING KHAKI KICKED KICKER KICKS KIDDED KIDDIE KIDDO KILLED KILLS KILNS KIMONO KINDS KINGS KINKS KIOSK KISSED KISSER KISSES KITED KITER KITES KITSCH KITTY KIWIS KLUTZ KNAVE KNAVES KNEAD KNEADS KNEED KNEEL KNEEL KNELL KNELT KNEW KNICKERS KNIFE KNIFED KNIFES KNIGHT KNIT KNITS KNOBS KNOCK KNOCKS KNOLL KNOTS KNOTTED KNOWN KNOWS KOALA KOOKS KOOKY KOSHER KOTOW KRAALS KRAIT KRAUT KRILL KRONE KRONOR KUDOS KUDZU KYRIE
LABEL LABOR LACED LACES LACEY LACKS LADEN LADER LADIES LADY LAGER LAGOON LAID LAIRS LAITY LAKES LAMAS LAMBS LAMED LAMER LAMES LAMPS LANCE LANDED LANDS LANES LANKY LAPED LAPEL LAPIS LAPSE LARCH LARDS LARDY LARGE LARGO LARKS LARVA LARYNX LASED LASER LASES LASSO LASTS LATEX LATIN LATCH LATER LATEX LATHE LATTE LAUGH LAUREL LAVA LAVAS LAVED LAVES LAVISH LAWNS LAWYER LAYER LAYLA LAYS LAZED LAZES LAZIER LAZILY LAZY LEACH LEADS LEAFY LEAGUE LEAKED LEAKS LEAKY LEANS LEANT LEAPS LEAPT LEARN LEASE LEASH LEAST LEAVE LEDGE LEECH LEERS LEERY LEFTS LEGAL LEGER LEMME LEMON LEMUR LEND LENDS LENTS LEONA LEONE LEORS LEPER LESSON LETHE LEVEE LEVEL LEVER LEVIS LIANA LIARS LIBEL LIBRA LICIT LIDDED LIDOS LIEGE LIEN LIENS LIFE LIFTS LIGHT LIKABLE LIKED LIKEN LIKER LIKES LILAC LILTS LILY LIMBO LIMBS LIMES LIMEY LIMIT LIMNS LIMPS LINED LINEN LINER LINES LINGO LINKS LIONS LIPID LISP LISPS LISTS LIVED LIVEN LIVER LIVES LIVID LLAMA LOADS LOAFS LOAMY LOANS LOATH LOBBY LOBED LOBES LOCAL LOCKED LOCKS LOCO LOCOS LOCUS LODES LODGE LOFTS LOFTY LOGIC LOGIN LOGOS LOINS LONER LONGED LONGS LOOFAH LOOKED LOOKS LOOMS LOONS LOONY LOOPED LOOPS LOOPY LOOSE LOOTED LOOTS LOPED LOPES LORDS LORE LORES LORRY LOSER LOSES LOST LOSTS LOTOS LOTTO LOTUS LOUSE LOUSY LOUTS LOVED LOVER LOVES LOWED LOWER LOWLY LOYAL LUCID LUCK LUCKY LUFFS LUGER LULL LULLED LULLS LUMBER LUMEN LUMPS LUMPY LUNAR LUNCH LUNDS LUNGE LUNGS LUNKS LUPIN LUPUS LURCH LURED LURES LURID LUSTS LUSTY LUTES LUXES LYING LYMPH LYNCH LYRES LYRIC
MACAW MACES MACHO MACKS MACRO MADAM MADLY MADAMS MAGIC MAGMA MAIDS MAILS MAIMS MAINE MAINS MAJOR MAKER MAKES MALES MAMAS MAMBA MAMBO MAMMA MAMMY MANED MANES MANIA MANIC MANGER MANGE MANIA MANIAC MANIA MANKIND MAORI MAPLE MARES MARSH MARTS MASKS MASON MASTS MATCH MATEY MATHS MATTE MAUVE MAVEN MAVIN MAWED MAYHEM MAYO MAYOR MAYS MEADS MEANS MEANT MEDAL MEDIA MEDIC MEETS MELON MENDS MENSA MERCY MERGE MERIT MESAS METAL METER METES METIS METRO METHS MEZZO MICRO MIDST MIENS MIGHT MIKES MILER MILES MILK MILKED MILKS MILKY MILLS MIMIC MIMES MINCE MINDS MINED MINER MINES MINIM MINIS MINKS MINOR MINOS MINTS MINUS MIRED MIRES MIRKS MIRTH MISER MISES MISO MISOS MISSED MITER MITES MIXED MIXER MIXES MOANS MOATS MOCHA MOCKS MODEM MODES MODI MOIRE MOIST MOLAR MOLAS MOLD MOLDS MOLDY MOLLS MOLTS MOMMA MOMMY MONEY MONKS MONTH MOODS MOODY MOONS MOOSE MOOTS MOPED MOPER MOPES MORAL MORES MORNS MORON MOSEY MOSES MOSSES MOSSY MOTEL MOTET MOTHS MOTIF MOTOR MOTTO MOULD MOUND MOUNT MOURN MOUSE MOUSY MOUTH MOVED MOVER MOVES MOVIE MOWED MOWER MOXIE MUCKS MUCKY MUDDY MUFFS MULES MULLS MUMMY MUMPS MUNCH MURAL MUSED MUSES MUSHY MUSIC MUSKY MUSTS MUSTY MUTED MUTES MUZZLE MYRRH MYTHS
NABBED NABOB NACRE NACHOS NADIR NAGGED NAGGY NAIAD NAILED NAILS NAIVE NAKED NAMED NAMES NANAS NAPES NAPPED NAPPER NAPPY NARCS NARDS NARROW NASAL NASTY NATTY NAVAL NAVEL NAVES NEAPS NEARS NEATS NECKS NEEDS NEEDY NEGRO NEIGH NEONS NEPAL NEPER NERDS NERDY NERVE NERVY NESTS NEVADA NEWBORN NEWEL NEWER NEWLY NEWS NEXT NICER NICHE NICKS NIECE NIFTY NIGHT NIHIL NINES NINON NINTH NITER NIVAL NIXED NIXES NOBLE NOBLY NODES NOIRS NOISE NOISY NOMAD NOMES NONCE NONES NOOKS NOONS NOOSE NORM NORMS NORTH NOSED NOSES NOSEY NOTCH NOTED NOTES NOUGAT NOUNS NOVAS NOVEL NUDGE NUDES NUKED NUKES NULLS NUMBED NUMBER NUNS NURDS NURSE NUTSO NYLON
OASES OASIS OASYS OATEN OATHS OBESE OBEYS OBOES OCEAN OCHRE OCTAL OCTET OCULAR ODDLY ODES ODIUM OFFAL OFFED OFFER OFFICE OFFS OGLED OGLER OGLES OGRE OGRES OHIOS OILED OILER OINKS OKAPI OKAYS OLDEN OLDER OLDIE OLIVE OMBRE OMEGA OMENS OMITS ONION ONSET OOMPH OOZED OOZES OPAH OPALS OPENED OPENER OPENS OPERA OPINE OPIUM OPTED OPTIC ORALS ORATE ORBIT ORCAS ORDER OREGON ORGAN OREO ORIBI ORIEL ORION OTHER OTTER OUGHT OUNCE OUTDO OUTED OUTER OUTGO OUZEL OUZOS OVALS OVENS OVERT OWING OWNED OWNER OXIDE OXLIP OZONE OZARK OZZIE
PACED PACER PACES PACHA PACKS PADRE PAEAN PAGAN PAGED PAGER PAGES PAGED PAGER PAIDS PAILS PAINS PAINT PAIRED PAIRS PALED PALER PALES PALMS PALMY PANDA PANED PANELS PANES PANGS PANIC PANTS PAPAS PAPAW PAPER PARDS PARES PARK PARKS PARRY PARSE PARTS PARTY PASTA PASTE PASTS PASTY PATCH PATEN PATER PATES PATHS PATIO PATIENT PATIN PATTY PAUSE PAVED PAVER PAVES PAWED PAWNS PAYED PAYEE PAYER PAYNE PAYS PEACE PEACH PEAKS PEAKY PEALS PEARL PEARS PEATS PEATY PECKS PEDAL PEEKED PEEKS PEELS PEERS PEEVE PELTS PENAL PENCE PENNED PENNY PENS PEONS PERCH PERIL PERKS PERKY PERMS PERPS PESKY PESTO PESTS PETAL PETER PETIT PETROL PETTY PEWS PHAGE PHASE PHIAL PHILS PHLEGM PHONE PHONIC PHONS PHONY PHOOEY PHOTO PHOTONS PHOTOS PHYLA PIANO PICKS PIECE PIEDS PIERS PIETY PIGGY PIKED PIKER PIKES PILAF PILAR PILE PILED PILEUM PILES PILLS PILOT PIMPS PINCH PINED PINES PINEY PINGED PINGER PINGO PINGS PINKS PINKO PINKY PINTO PINTS PINUP PIOUS PIPED PIPER PIPES PIPET PIQUE PISTS PITCH PITHS PITHY PIVOT PIXEL PIXES PIZZA PLACE PLAID PLAIN PLAIT PLANE PLANK PLANS PLANT PLASMA PLATE PLAYED PLAYER PLAYS PLAZA PLEAD PLEAS PLEAT PLEBS PLEDGE PLENA PLIED PLODS PLOPS PLOTS PLOWS PLOY PLOYS PLUCK PLUGS PLUMB PLUME PLUMP PLUMS PLUNK PLURALS PLUSES PLUSH PODGE PODGY POEMS POETIC POETRY POETS POGO POGOS POINT POISE POKED POKER POKES POKEY POLAR POLED POLES POLIO POLISH POLKA POLLS POLOS POLYP POMP POMPS PONDS PONIES PONS POODLE POOLS POOPS POOR POPES POPPY PORCH PORES PORK PORKS PORTS POSED POSER POSES POSIT POSSE POSTS POTPIE POTLUCK POTS POTTY POUCH POUNCE POUND POUR POURED POURS POUTS POWER POWERED POXES PRANK PRAWN PRAYED PRAYER PRAYS PREEN PREFIX PREP PRESS PRICE PRICY PRIDE PRIED PRIES PRIEST PRIM PRIMER PRIMES PRINCE PRINK PRINT PRION PRIORS PRISMS PRISON PRISSY PRIVY PRIZE PROBE PROBES PROFS PROGS PRONE PRONG PROOF PROPS PROSE PROSO PROSY PROTON PROUD PROVE PROWL PROWLS PROXY PRUDE PRUNE PRUNES PSALM PSEUD PSHAW PSYCH PUBES PUBIC PUBIS PUDGY PUFFS PUFFY PUGGY PUKED PUKES PUKING PULL PULLED PULLER PULLEY PULLING PULLS PULPED PULPIT PULPS PULPY PULSE PULSED PULSER PULSES PUMA PUMICE PUMP PUMPED PUMPER PUMPS PUNCH PUNCHED PUNCHES PUNDIT PUNGED PUNK PUNKED PUNKER PUNKS PUNNED PUNS PUNSTER PUNTS PUNY PUPIL PUPILS PUPPED PUPPY PURE PURED PUREE PUREES PURER PUREST PURGE PURGED PURGES PURIM PURINE PURISTS PURITAN PURITY PURL PURLED PURLS PURPLE PURRED PURRS PURSE PURSED PURSER PURSES PURSUE PURVIEW PUSHED PUSHER PUSHES PUSHIER PUSHILY PUSHING PUSHUP PUSHY PUSSY PUTTED PUTTERED PUTTERS PUTTY PUZZLE PUZZLED PUZZLER PUZZLES PYLON PYRES PYRRHIC PYTHON PYTHONS
QUADS QUAFF QUAIL QUAINT QUAKE QUAKED QUAKES QUAKING QUALMS QUARRY QUARTS QUARTZ QUASH QUAYS QUEEN QUEER QUELL QUERY QUEST QUEUE QUEUED QUEUES QUICK QUID QUIET QUIETED QUIETS QUIFFS QUILL QUILT QUINCE QUINCY QUIPS QUIRK QUIRT QUITE QUIVER QUOIT QUOITS QUOTA QUOTE QUOTED QUOTES QUOTHS
RABBI RABID RACED RACER RACES RACK RACKED RACKET RACKS RADAR RADIO RAFTS RAGED RAGES RAGGY RAID RAIDED RAIDER RAIDS RAILS RAINS RAINY RAISE RAKED RAKES RALLY RAMP RAMPS RANCH RANDY RANGE RANGED RANGER RANGES RANGS RANI RANIS RANK RANKED RANKER RANKING RANKS RANTED RANTERS RANTS RAPED RAPES RAPID RAPS RAPTS RARED RARER RARES RASH RATED RATER RATES RATIO RATIOS RATS RATTY RAVED RAVEN RAVER RAVES RAVING RAYED RAYS RAYON RAZED RAZER RAZES RAZOR REACH REACT READ READER READS READY REALM REAMS REAPS REARM REARS REAVE REBEL REBID REBUS REBUT RECAP RECON REDDY REDID REEDS REEFS REEKS REELS REFER REFIT REFIX REGAL REGS REIGN REINS REIVE RELAX RELAY RELIC REMIT RENAL RENEW RENTS REPAY REPEL REPLY RERAN RERUN RESAY RESEE RESET RESH RESHIP RESID RESIN REST RESTS RETCH RETRO REVEL REVET REVIVAL REVUE RHEUM RHINO RHUMB RHYMES RHYME RIBBED RIBBONS RIBS RICED RICES RICH RICK RICKS RIDDED RIDDEN RIDDLE RIDER RIDES RIDGE RIDS RIFE RIFER RIFFS RIFLE RIFTS RIGHT RIGID RIGS RILED RILES RIMED RIMES RIND RINDS RINGED RINGER RINGS RINKS RINSE RIOJA RIOT RIOTED RIOTS RIPEN RIPER RIPPED RIPS RISEN RISER RISES RISKED RISKS RISKY RITES RITUAL RITZY RIVAL RIVALS RIVED RIVEL RIVER RIVERS RIVET ROACH ROAD ROADS ROADIE ROAM ROAMED ROAMER ROAMS ROANS ROAR ROARED ROARS ROAST ROBED ROBES ROBIN ROBOT ROBOTS ROCK ROCKED ROCKET ROCKETS ROCKY RODEO ROILED ROILS ROLED ROLES ROLF ROLLED ROLLERS ROLLING ROLLS ROMAN ROMP ROMPED ROMPING ROMPS ROND ROOD ROOFED ROOFER ROOFING ROOFS ROOK ROOKED ROOKERY ROOKIES ROOKS ROOM ROOMED ROOMER ROOMS ROOST ROOSTED ROOSTER ROOSTS ROOT ROOTED ROOTER ROOTING ROOTS ROPE ROPED ROPER ROPES ROPING ROSCOE ROSE ROSEATE ROSEBUD ROSES ROSY ROTA ROTAS ROTATE ROTC ROTE ROTES ROTOR ROTORS ROTS ROTUND ROUGE ROUGH ROUND ROUNDED ROUND ROUSE ROUT ROUTE ROUTED ROUTER ROUTERS ROUTES ROUTING ROUTS ROVE ROVED ROVES ROVING ROW ROWDY ROWED ROWERS ROWING ROWS ROYAL RUBBED RUBBER RUBE RUBIES RUBLE RUBY RUDDER RUDDY RUDE RUE RUED RUES RUFF RUFFED RUFFLE RUGS RUIN RUINED RUINS RULE RULED RULER RULERS RULES RULING RUM RUMBLE RUMMY RUMP RUMPS RUMP RUMS RUN RUNG RUNGS RUNNER RUNT RUNTS RUNTY RUPEE RUPEES RUPIAH RURAL RUSE RUSED RUSES RUSH RUSHED RUSHES RUSK RUSSET RUSSIA RUSSO RUST RUSTED RUSTIC RUSTS RUSTY RUTS RUTTED RUTTING RYE RYES
SABER SABLE SABRA SACHA SACKS SACKED SACS SADLY SAFER SAFES SAGAS SAGE SAGES SAGGED SAGGY SAID SAILED SAILS SAILED SAINT SAINTLY SAINTS SAKE SAKER SAKES SALAD SALE SALES SALIVA SALKS SALLY SALMI SALON SALSA SALTS SALTY SALVE SALVES SAME SAMENESS SAMOA SAMOS SAMPLE SANDY SANDS SANE SANELY SANER SANEST SANG SANK SAPPY SARGE SARI SARIS SASH SASS SASSED SASSING SATIN SATIRE SATYR SAUCE SAUCED SAUCER SAUCES SAUNA SAVE SAVED SAVER SAVES SAVING SAVIORS SAVOR SAWED SAWING SAWS SAWYER SAX SAYINGS SAYS SCABS SCALD SCALE SCALP SCAMS SCANS SCANT SCARE SCARF SCARS SCARY SCATS SCENE SCENT SCHWA SCION SCOFF SCOOP SCOOT SCOPE SCORCH SCORED SCORES SCORN SCOTS SCOUR SCOUT SCOWL SCOWS SCRAM SCRAP SCREE SCREW SCRIM SCRIP SCRUB SCRUM SCUBA SCUFF SCUM SCUMS SCUNNER SCUPS SEAL SEALED SEALS SEAMS SEAMY SEAR SEARS SEAS SEAT SEATED SEATS SECEDE SEDAN SEDGE SEDGY SEDUM SEED SEEDS SEEDY SEEING SEEK SEEKER SEEKS SEEM SEEMED SEEMS SEEN SEEPS SEER SEES SEETHE SEGUE SEINE SEISE SEISM SEIZE SEIZED SELDOM SELL SELLER SELLS SELVAGE SELVES SEMIS SENDS SENIOR SENORA SENSE SENT SEPSIS SEPTA SEPTS SEQUEL SERA SERAC SERAGLIO SERAI SERAPE SERFS SERGE SERIES SERIF SERMON SERS SERUM SERVE SERVED SERVER SERVERS SERVES SERVING SETAE SETON SETS SETTERS SETTING SETUP SEVEN SEVERE SEVERED SEVERS SEWED SEWER SEWERS SEWING SEWN SEX SHAD SHADE SHADES SHADIER SHADOWS SHADOWY SHADY SHAFT SHAG SHAGGY SHAH SHAKE SHAKES SHAKEN SHAKER SHAKY SHALE SHALL SHALOM SHAME SHAMP SHANK SHAPE SHAPED SHAPES SHARD SHARDS SHARE SHARED SHARES SHARK SHARKS SHARP SHARPS SHAVE SHAVED SHAVERS SHAVES SHAVING SHAWL SHAWLS SHAY SHE SHEAF SHEAR SHEARED SHEARING SHEARS SHEATH SHED SHEDS SHEEP SHEER SHEERS SHEET SHEETED SHEETING SHEETS SHEIK SHEIKHS SHEIKS SHELF SHELL SHELLED SHELLER SHELLS SHELTERS SHELVES SHEPHERDS SHEPHERDS SHERBETS SHERIFFS SHERPA SHERRY SHIFT SHIFTED SHIFTING SHIFTS SHIFTY SHILLED SHILLS SHIM SHIMMER SHIMMERED SHIMMERING SHIMMERS SHIMS SHIN SHINE SHINED SHINER SHINES SHINNING SHINS SHINY SHIP SHIPMATES SHIPPED SHIPPING SHIPS SHIRE SHIRES SHIRKED SHIRKS SHIRR SHIRT SHIRTS SHITE SHIVAS SHIVER SHIVERED SHIVERS SHIVES SHOAL SHOAT SHOAT SHOCK SHOCKED SHOCKING SHOCKS SHOD SHODDY SHOE SHOED SHOES SHOELACES SHONE SHOO SHOOED SHOOTS SHOPLIFTERS SHOPLIFTING SHOPPED SHOPPER SHOPPING SHOPS SHORE SHORED SHORES SHORN SHORT SHORTAGE SHORTAGES SHORTED SHORTEN SHORTER SHORTLY SHORTS SHOT SHOTGUN SHOTGUNS SHOTS SHOULD SHOULDER SHOULDERED SHOULDERING SHOULDERS SHOULDN'T SHOUT SHOUTED SHOUTING SHOUTS SHOVE SHOVED SHOVEL SHOVELED SHOVELING SHOVELS SHOVES SHOVING SHOW SHOWBOAT SHOWCASE SHOWCASED SHOWCASING SHOWED SHOWER SHOWERED SHOWERING SHOWERS SHOWGIRL SHOWGIRLS SHOWIER SHOWILY SHOWING SHOWN SHOWS SHOWY SHRANK SHRED SHREDDED SHREDDING SHREDS SHREW SHREWD SHREWDLY SHREWS SHRIEKED SHRIEKING SHRIEKS SHRIFT SHRIKE SHRILL SHRIMP SHRINE SHRINK SHRINKING SHROUDED SHRUB SHRUG SHRUGGED SHRUGS SHRUNK SHUCK SHUDDER SHUDDERED SHUDDERING SHUDDERS SHUFFLE SHUN SHUSH SHUT SHUTDOWN SHUTDOWNS SHUTTLE SHUTTLED SHUTTLES SHY SHYLY SHYNESS SIAMESE SIBYL SIC SICILY SICK SICKBED SICKEN SICKENED SICKENING SICKLE SICKLY SICKNESS SIDE SIDED SIDEBAR SIDED SIDEKICK SIDESHOWS SIDESTEP SIDESTEPS SIDESTEPPED SIDESTEPPING SIDESTEP SIDEWALK SIDEWALL SIDEWAYS SIDEWISE SIDING SIDLE SIDLED SIDLES SIDLING SIEGE SIEGES SIERRA SIESTA SIESTAS SIEVE SIEVED SIEVES SIEVING SIFT SIFTED SIFTERS SIFTING SIFTS SIGH SIGHED SIGHING SIGHS SIGHT SIGHTED SIGHTING SIGHTLESS SIGHTLY SIGHTS SIGN SIGNAL SIGNALED SIGNALING SIGNALLED SIGNALS SIGNED SIGNER SIGNERS SIGNET SIGNIFY SIGNIFIED SIGNIFYING SIGNIFY SIGNING SIGNORA SIGNORE SIGNORINA SIGNORS SIGNORS SIGNPOST SIGNPOSTED SIGNPOSTING SIGNPOSTS SIGNS SIKHISM SIKH SIKHS SILAGE SILDOWN SILED SILENCE SILENT SILK SILKEN SILKIER SILKILY SILKINESS SILKS SILKWORM SILKWORMS SILKY SILLED SILLY SILO SILVAN SIMPLE SINGE SINGS
""".split())

# Music-themed bias set
MUSIC = set("ADELE ALBUM ARENA BANJO BASSO BEATS BEBOP BLUES BONGO BOWIE BRASS BRAVO BUGLE CANON CAPOS CAROL CELLO CHANT CHIME CHOIR CHORD CLEFS CLINK COMBO CONGA COVER CRADLE DANCE DEMOS DIRGE DISCO DITTY DIVAS DJINN DRAKE DRAMA DRESS DREAM DRIVE DROPS DRUMS DUETS DUMBO DYLAN EAGLE EDDIE ELITE ELOPE ELTON ELVIS EMCEE EMOTE ENJOY ENTER EQUAL EQUIP ETHEL EVENT EVITA EXTRA FLUTE FORTE GENRE GUEST HARPS HEAVY HELLO HONOR HOUSE HYMNS IDOLS JAZZY KAZOO LATIN LAYLA LEMON LILAC LOVER LOWER LYRES LYRIC MAJOR METAL METER METRO MEZZO MINOR MODEM MOVIE MUSED MUSES MUSIC NOISE NOTES OASIS OBOES OPERA ORGAN PIANO PLAYS PRIDE PRIME PRIZE PSALM PUNKS QUEEN RADIO RAPS REGGAE REMIX RHYME RIFFS RIOTS RIVER ROCKS ROUND SAMBA SCALE SCORE SINGS SOLOS SONGS SONIC SOULS STARS STING STYLE SUITE SUPER SWING TANGO TEMPO TENOR THIRD TIMER TONAL TONES TUBAS TUNES VIDEO VIOLA VOCAL VOICE WALTZ".split())

WORDS_5 = sorted(w for w in WORDS if isinstance(w, str) and len(w) == 5 and w.isalpha())
# Trim awkward plurals of proper nouns / abbreviations / obscure
BANNED = {'IOWAS', 'OHIOS', 'OASYS', 'KAYOS', 'GAYS', 'JOEYS', 'JESUS', 'BOYS',
          'EWING', 'ELLEN', 'ELLIE', 'ELLIS', 'HAYES', 'HESSE', 'INDIA', 'ITALY',
          'JONES', 'KENYA', 'MAINE', 'NEPAL', 'SAMOA', 'GHANA', 'SACHA', 'JANES',
          'EWERS', 'DIDOS', 'PAYNE', 'JULIA', 'JULIE', 'JONAH', 'JESTS', 'JEWS',
          'AKINS', 'BREDA', 'BREDS', 'CATHY', 'EDDIE', 'ELENA', 'ELMER', 'ERICA',
          'IRENE', 'JINNI', 'JATOS', 'PHILS', 'OZZIE', 'IOWAS', 'IXIAS', 'LEONA',
          'LEORS', 'LEVIS', 'MARYL', 'MARYS', 'MAORI', 'OASYS', 'IGUANA', 'CAFES',
          'GAOL', 'EBBED', 'DJINN', 'RIOJA', 'MARUS', 'JADED', 'JAINS', 'EATIN',
          'IXIA', 'OZARK'}
WORDS_5 = [w for w in WORDS_5 if w not in BANNED]
MUSIC = {w for w in MUSIC if len(w) == 5 and w.isalpha() and w not in BANNED}

# Pos-letter lookup
POS_MAP = defaultdict(set)
for w in WORDS_5:
  for i, ch in enumerate(w):
    POS_MAP[(i, ch)].add(w)

def all_words_for_pattern(p):
  # p is a 5-char string with letters or None
  result = None
  for i, ch in enumerate(p):
    if ch is None:
      continue
    s = POS_MAP[(i, ch)]
    result = s if result is None else (result & s)
    if not result:
      return set()
  return result if result is not None else set(WORDS_5)

def solve(rows, cols, used):
  """Pick the slot (row or col) with fewest candidates, branch on each."""
  if all(rows) and all(cols):
    return rows[:], cols[:]
  best = None
  best_options = None
  for i in range(5):
    if not rows[i]:
      pattern = [(cols[j][i] if cols[j] else None) for j in range(5)]
      opts = all_words_for_pattern(pattern) - used
      if best_options is None or len(opts) < len(best_options):
        best, best_options = ('R', i), opts
        if not opts:
          return None
  for i in range(5):
    if not cols[i]:
      pattern = [(rows[j][i] if rows[j] else None) for j in range(5)]
      opts = all_words_for_pattern(pattern) - used
      if best_options is None or len(opts) < len(best_options):
        best, best_options = ('C', i), opts
        if not opts:
          return None
  kind, idx = best
  # Sort candidates to prefer music words first
  sorted_opts = sorted(best_options, key=lambda w: (0 if w in MUSIC else 1, w))
  for w in sorted_opts:
    if kind == 'R':
      rows[idx] = w
    else:
      cols[idx] = w
    used.add(w)
    result = solve(rows, cols, used)
    if result:
      return result
    if kind == 'R':
      rows[idx] = None
    else:
      cols[idx] = None
    used.remove(w)
  return None

t0 = time.time()
# Try seeding row 0 with various music words for thematic variety
music5 = sorted(w for w in MUSIC if w in set(WORDS_5))
# Try the famous ones first
priority = ['ADELE', 'BOWIE', 'DRAKE', 'DYLAN', 'ELTON', 'ELVIS', 'EDDIE',
            'PIANO', 'BANJO', 'CELLO', 'BLUES', 'BEATS', 'CHORD', 'CHOIR',
            'LATIN', 'LAYLA', 'OPERA', 'TEMPO', 'TANGO', 'TENOR', 'LYRIC',
            'METAL', 'METRO', 'NOTES', 'PSALM', 'RADIO', 'SCALE', 'SCORE',
            'SONGS', 'STING', 'SWING', 'TUNES', 'VOCAL', 'VIOLA', 'HYMNS']
priority = [w for w in priority if w in set(WORDS_5)]
others = [w for w in music5 if w not in priority]
random.seed(20260513)
random.shuffle(others)
music5 = priority + others

solution = None
for seed in music5:
  rows = [None]*5; cols = [None]*5
  rows[0] = seed
  result = solve(rows, cols, {seed})
  if result:
    solution = result
    print(f'Seeded row 0 = {seed}')
    break
  if time.time() - t0 > 30:
    print('timeout')
    break

if not solution:
  print('NO SOLUTION')
  sys.exit(1)

rows, cols = solution
print(f'\nSolved in {time.time()-t0:.2f}s')
print('Grid:')
for r in range(5):
  print('  ' + ' '.join(rows[r]))

# Verify
for c in range(5):
  col_word = ''.join(rows[r][c] for r in range(5))
  if col_word != cols[c]:
    print(f'MISMATCH col {c}: {col_word} != {cols[c]}')
    sys.exit(1)
print('\nVerified ✓')
print(f'Across: {rows}')
print(f'Down:   {cols}')

# Output JSON for the front-end
out = {
  'size': 5,
  'across': rows,
  'down': cols,
}
import json
with open('puzzle.json', 'w') as f:
  json.dump(out, f, indent=2)
print('Wrote puzzle.json')
